NAME := provisioner

$(NAME)_COMPONENTS  += bluetooth.bt_host bluetooth.bt_mesh yloop cli

$(NAME)_INCLUDES += ../ \
					../../../../network/bluetooth/bt_mesh/inc/api \
					../../../../network/bluetooth/bt_mesh/inc/api/mesh \
					../../../../network/bluetooth/bt_host/bt_common/include/common \
					../../../../network/bluetooth/bt_mesh \

$(NAME)_SOURCES  := main.c	\
					application.c

en_bt_smp = 1
bt_host_tinycrypt = 1

# Host configurations
GLOBAL_DEFINES += CONFIG_BLUETOOTH
GLOBAL_DEFINES += CONFIG_BT_CONN
GLOBAL_DEFINES += CONFIG_BT_PERIPHERAL

# Mesh function select
GLOBAL_DEFINES += CONFIG_BT_MESH
GLOBAL_DEFINES += CONFIG_BT_MESH_PB_ADV
GLOBAL_DEFINES += CONFIG_BT_MESH_PB_GATT
GLOBAL_DEFINES += CONFIG_BT_MESH_PROXY
GLOBAL_DEFINES += CONFIG_BT_MESH_GATT_PROXY
GLOBAL_DEFINES += CONFIG_BT_MESH_RELAY
GLOBAL_DEFINES += CONFIG_BT_CENTRAL
GLOBAL_DEFINES += CONFIG_BT_MESH_PROVISIONER
# GLOBAL_DEFINES += CONFIG_BT_MESH_SHELL
GLOBAL_DEFINES += CONFIG_BT_GATT_CLIENT

# Mesh foundation model select
GLOBAL_DEFINES += CONFIG_BT_MESH_CFG_CLI
GLOBAL_DEFINES += CONFIG_BT_MESH_CFG_SRV
GLOBAL_DEFINES += CONFIG_BT_MESH_HEALTH_SRV
GLOBAL_DEFINES += CONFIG_BT_MESH_GEN_ONOFF_CLI
#GLOBAL_DEFINES += CONFIG_BT_MESH_ALI_TMALL_GENIE

GLOBAL_DEFINES += CONFIG_INFO_DISABLE

#MESH_MODEL_VENDOR_SRV = 1

GLOBAL_DEFINES += CONFIG_BT_DEVICE_NAME=\"Beken_provisioner\"

# Debug feature configurations
#GLOBAL_DEFINES += CONFIG_BT_MESH_DEBUG_PROVISIONER
