NAME := provisioner

$(NAME)_COMPONENTS  += bluetooth.bt_host bluetooth.bt_mesh yloop cli

$(NAME)_INCLUDES += ../ \
					../../../../network/bluetooth/bt_mesh/inc/api \
					../../../../network/bluetooth/bt_mesh/inc/api/mesh \
					../../../../network/bluetooth/bt_host/bt_common/include/common \

$(NAME)_SOURCES  := main.c	\
					application.c

#ble = 1
#bt_mesh = 1
en_bt_smp = 1

bt_host_tinycrypt = 1

# Host configurations
GLOBAL_DEFINES += CONFIG_BLUETOOTH
GLOBAL_DEFINES += CONFIG_BT_CONN
GLOBAL_DEFINES += CONFIG_BT_PERIPHERAL

# Mesh function select
GLOBAL_DEFINES += CONFIG_BT_MESH
GLOBAL_DEFINES += CONFIG_BT_MESH_PB_ADV
GLOBAL_DEFINES += CONFIG_BT_MESH_PB_GATT
GLOBAL_DEFINES += CONFIG_BT_MESH_PROXY
GLOBAL_DEFINES += CONFIG_BT_MESH_GATT_PROXY
GLOBAL_DEFINES += CONFIG_BT_MESH_RELAY
GLOBAL_DEFINES += CONFIG_BT_CENTRAL
GLOBAL_DEFINES += CONFIG_BT_MESH_PROVISIONER
GLOBAL_DEFINES += CONFIG_BT_MESH_CFG_CLI
GLOBAL_DEFINES += CONFIG_BT_MESH_SHELL
GLOBAL_DEFINES += CONFIG_BT_GATT_CLIENT

# Mesh foundation model select
GLOBAL_DEFINES += CONFIG_BT_MESH_CFG_SRV
GLOBAL_DEFINES += CONFIG_BT_MESH_HEALTH_SRV
GLOBAL_DEFINES += MESH_MODEL_HSL_SRV
GLOBAL_DEFINES += CONFIG_BT_MESH_GEN_ONOFF_CLI
#GLOBAL_DEFINES += CONFIG_BT_MESH_ALI_TMALL_GENIE

GLOBAL_DEFINES += CONFIG_INFO_DISABLE

GLOBAL_INCLUDES += ../

MESH_MODEL_GEN_ONOFF_SRV = 1
MESH_MODEL_LIGHTNESS_SRV = 1
MESH_MODEL_GEN_ONPOWERUP_SRV = 1
MESH_MODEL_CTL_SRV = 1
#MESH_MODEL_VENDOR_SRV = 1
MESH_MODEL_HSL_SRV = 1
ALI_SIMPLE_MODLE = 1



GLOBAL_DEFINES += CONFIG_BT_DEVICE_NAME=\"Beken_provisioner\"

GLOBAL_DEFINES += PROJECT_SW_VERSION=0x00010104
#GLOBAL_DEFINES += PROJECT_SECRET_KEY=\"00112233445566770011223344556677\"

# Feature configurations
GLOBAL_DEFINES += CONFIG_BT_MESH_DEBUG_LIGHT
#GLOBAL_DEFINES += CONFIG_BT_MESH_DEBUG_FLASH
GLOBAL_DEFINES += CONFIG_BT_MESH_DEBUG_EVENT
