#include "uart_pub.h"

#define STDIO_UART_PORT     UART1_PORT
#define STDIO_UART_BUADRATE 1000000

#define PARTITION_STACK_CPU_ADDR    (0x1F00)
#define PARTITION_APP_CPU_ADDR      (0x16A00)
#define PARTITION_OTA_BAC_CPU_ADDR  (0x45B00)

#define PARTITION_STACK_CRC_ADDR        ((PARTITION_STACK_CPU_ADDR)*0x22/0x20)      //0x20F0
#define PARTITION_APP_CRC_ADDR          ((PARTITION_APP_CPU_ADDR)*0x22/0x20)        //0x170B0
#define PARTITION_OTA_TEMP_CRC_ADDR     ((PARTITION_OTA_BAC_CPU_ADDR)*0x22/0x20)
